// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'AIzaSyCSch9upZP9qYVj8ZSrQm8mRDtZWs7_AOw',
    appId:             '1:418130924506:android:cf4cfe9e5e041d23a726e3',
    messagingSenderId: '418130924506',
    projectId:         'werlog-c52b7',
    storageBucket:     'werlog-c52b7.firebasestorage.app',
  );

  // ── iOS placeholder — add your iOS app in Firebase Console
  // and replace these values with your real google-services iOS plist values
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'AIzaSyCSch9upZP9qYVj8ZSrQm8mRDtZWs7_AOw',
    appId:             '1:418130924506:ios:REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '418130924506',
    projectId:         'werlog-c52b7',
    storageBucket:     'werlog-c52b7.firebasestorage.app',
    iosBundleId:       'com.app.werlog',
  );
}